RemoteToolServer/ViewModels/HomeViewModel.cs
using RemoteToolData.Data;
using X.PagedList;

namespace RemoteTool.Server.ViewModels
{
    public class HomeViewModel
    {
        public string? OperaMsg { get; set; } = string.Empty;
        public int DeviceCount { get; set; } 
        public int ProjectCount { get; set; }
        public int PageCount { get; set; }
        public int PageNumber { get; set; }

        public IPagedList<DeviceInfo>? DeviceInfos { get; set; }
    }
}

RemoteToolServer/Controllers/DeviceController.cs
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RemoteTool.Common;
using RemoteTool.Server.ViewModels;
using RemoteToolData.Data;
using X.PagedList;

namespace RemoteTool.Server.Controllers
{
    public class DeviceController : Controller
    {
        private readonly ILogger<DeviceController> logger;
        private readonly ApplicationDbContext applicationDbContext;

        public DeviceController(ILogger<DeviceController> logger, ApplicationDbContext applicationDbContext)
        {
            this.logger = logger;
            this.applicationDbContext = applicationDbContext;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Delete(string guidCode)
        {
            var info = new DeviceInfo();

            if (guidCode == null)
            {
                info = applicationDbContext.DeviceInfos.Where(p => string.IsNullOrEmpty(p.GuidCode)).FirstOrDefault();
            }
            else
            {
                info = applicationDbContext.DeviceInfos.Where(p => p.GuidCode == guidCode).FirstOrDefault();
            }
            if (info == null)
            {
                ViewBag.ErrorMsg = $"找不到guidCode={guidCode}的设备";
                return View("~/Views/Error/Error.cshtml");
            }
            else
            {
                if (User?.Identity?.Name == info.CreatorName || User?.Identity?.Name == "lixing")
                {
                    applicationDbContext.DeviceInfos.Remove(info);
                    applicationDbContext.SaveChanges();
                }
                else
                {
                    ViewBag.ErrorMsg = $"设备创建者为{info.CreatorName}不是当前用户,无法进行删除！";
                    return View("~/Views/Error/Error.cshtml");
                }
            }

            try
            {
                var list = await applicationDbContext.DeviceInfos.ToListAsync();
                if (list?.Count > 0)
                {
                    SortedDictionary<string, DeviceInfo> dictionary = new SortedDictionary<string, DeviceInfo>();
                    foreach (var item in list)
                    {
                        if (dictionary.ContainsKey(item.ProjectName) == false)
                            dictionary.Add(item.ProjectName, item);
                    }

                    ViewBag.OperaMsg = $"总共查询到{list.Count}条结果，包含项目{dictionary.Keys.Count}个！";
                    var infos = list.ToPagedList<DeviceInfo>(1, HomeController.PageSize);
                    return RedirectToAction("index", "home", infos);
                }
                else
                {
                    ViewBag.OperaMsg = $"当前没有设备信息记录！";
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"查询设备信息发生异常->{ex.Message}");
            }
            return View();
        }

        public IActionResult Details(string guidCode)
        {
            var info = applicationDbContext.DeviceInfos.Where(p => p.GuidCode == guidCode).FirstOrDefault();
            var mode = info?.Adapt<DeviceInfoViewModel>();
            if (mode == null)
            {
                ViewBag.ErrorMsg = $"找不到guidCode={guidCode}的设备";
                return View("~/Views/Error/Error.cshtml");
            }
            else
            { return View(mode); }
        }

        public IActionResult Modify(string guidCode)
        {
            var info = applicationDbContext.DeviceInfos.Where(p => p.GuidCode == guidCode).FirstOrDefault();
            var mode = info?.Adapt<DeviceInfoViewModel>();
            if (mode == null)
            {
                ViewBag.ErrorMsg = $"找不到guidCode={guidCode}的设备";
                return View("~/Views/Error/Error.cshtml");
            }
            else
            { return View(mode); }
        }

        [HttpPost]
        public async Task<IActionResult> Save(DeviceInfoViewModel model)
        {
            if (ModelState.IsValid)
            {
                var info = new DeviceInfo();
                model.GuidCode = Guid.NewGuid().ToString("N");
                model.CreatorName = User.Identities.FirstOrDefault()?.Name;
                model.CreateTime = DateTime.Now;
                info.CopyObjValue<DeviceInfo>(model);
                applicationDbContext.Add(info);
                applicationDbContext.SaveChanges();
            }
            try
            {
                var list = await applicationDbContext.DeviceInfos.ToListAsync();
                if (list?.Count > 0)
                {
                    SortedDictionary<string, DeviceInfo> dictionary = new SortedDictionary<string, DeviceInfo>();
                    foreach (var item in list)
                    {
                        if (dictionary.ContainsKey(item.ProjectName) == false)
                            dictionary.Add(item.ProjectName, item);
                    }
                    //homeModel.DeviceCount = list.Count;
                    //homeModel.ProjectCount = dictionary.Keys.Count;
                    //homeModel.OperaMsg = $"总共查询到{list.Count}条结果，包含项目{dictionary.Keys.Count}个！";
                    //homeModel.DeviceInfos = await list.ToPagedListAsync(1, 10);
                    //homeModel.PageNumber = 1;
                    //homeModel.PageCount = homeModel.DeviceInfos.PageCount;

                    ViewBag.OperaMsg = $"总共查询到{list.Count}条结果，包含项目{dictionary.Keys.Count}个！";
                    var infos = list.ToPagedList<DeviceInfo>(1, HomeController.PageSize);
                    return RedirectToAction("index", "home", infos);
                }
                else
                {
                    ViewBag.OperaMsg = $"当前没有设备信息记录！";
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"查询设备信息发生异常->{ex.Message}");
            }
            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Modify(DeviceInfoViewModel model)
        {
            var info = applicationDbContext.DeviceInfos.Where(p => p.GuidCode == model.GuidCode).FirstOrDefault();
            if (info == null)
            {
                ViewBag.ErrorMsg = $"找不到guidCode={model.GuidCode}的设备";
                return View("~/Views/Error/Error.cshtml");
            }
            else
            {
                info.ProjectName = model.ProjectName;
                info.DeviceName = model.DeviceName;
                info.DeviceSerialNo = model.DeviceSerialNo;
                info.OraySunId = model.OraySunId;
                info.OraySunPsw = model.OraySunPsw;
                info.ToDeskId = model.ToDeskId;
                info.ToDeskPsw = model.ToDeskPsw;
                applicationDbContext.SaveChanges();

            }

            try
            {
                var list = await applicationDbContext.DeviceInfos.ToListAsync();
                if (list?.Count > 0)
                {
                    SortedDictionary<string, DeviceInfo> dictionary = new SortedDictionary<string, DeviceInfo>();
                    foreach (var item in list)
                    {
                        if (dictionary.ContainsKey(item.ProjectName) == false)
                            dictionary.Add(item.ProjectName, item);
                    }
                    ViewBag.OperaMsg = $"总共查询到{list.Count}条结果，包含项目{dictionary.Keys.Count}个！";
                    var infos = list.ToPagedList<DeviceInfo>(1, HomeController.PageSize);
                    return RedirectToAction("index", "home", infos);
                }
                else
                {
                    ViewBag.OperaMsg = $"当前没有设备信息记录！";
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"查询设备信息发生异常->{ex.Message}");
            }
            return View();
        }
    }
}

RemoteToolServer/Views/Home/ActivityLog.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>这里展示操作日志</p>

RemoteToolServer/Views/Home/Charts.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Charts</h1>
    <p class="mb-4">
        Chart.js is a third party plugin that is used to generate the charts in this theme.
        The charts below have been customized - for further customization options, please visit the <a target="_blank" href="https://www.chartjs.org/docs/latest/">
            official Chart.js
            documentation
        </a>.
    </p>

    <!-- Content Row -->
    <div class="row">

        <div class="col-xl-8 col-lg-7">

            <!-- Area Chart -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Area Chart</h6>
                </div>
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="myAreaChart"></canvas>
                    </div>
                    <hr>
                    Styling for the area chart can be found in the
                    <code>/js/demo/chart-area-demo.js</code> file.
                </div>
            </div>

            <!-- Bar Chart -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Bar Chart</h6>
                </div>
                <div class="card-body">
                    <div class="chart-bar">
                        <canvas id="myBarChart"></canvas>
                    </div>
                    <hr>
                    Styling for the bar chart can be found in the
                    <code>/js/demo/chart-bar-demo.js</code> file.
                </div>
            </div>

        </div>

        <!-- Donut Chart -->
        <div class="col-xl-4 col-lg-5">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Donut Chart</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-pie pt-4">
                        <canvas id="myPieChart"></canvas>
                    </div>
                    <hr>
                    Styling for the donut chart can be found in the
                    <code>/js/demo/chart-pie-demo.js</code> file.
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

RemoteToolServer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@using X.PagedList.Mvc.Core; @*import this so we get our HTML Helper*@
@using X.PagedList; @*import this so we can cast our list to IPagedList (only necessary because ViewBag is dynamic)*@
@using X.PagedList.Mvc.Core.Fluent
@using X.PagedList.Web.Common
@using RemoteToolData.Data
@model IPagedList<DeviceInfo> 
<!-- import the included stylesheet for some (very basic) default styling -->
<link href="/css/PagedList.css" rel="stylesheet" type="text/css" />
<div class="text-center">
    <h1 class="display-4">欢迎使用RemoteTool</h1>
    @*<p>总共查询到 @Model.DeviceCount 条结果，包含项目 @Model.ProjectCount 个！ </p>*@
    <p>@ViewBag.OperaMsg</p>
   
</div>
<div class="row">
    @if (Model != null)
    {
        @foreach (var item in Model)
        {
            <div class="card" style="width: 18rem;margin:10px">
                <div class="card-body">
                    <h5 class="card-title">@item.ProjectName</h5>
                    <h6 class="card-subtitle mb-2 text-muted">@item.DeviceName</h6>
                    <div class="form-group">
                        <span class="form-row">连接次数：@item.ToDeskCount</span>
                        <span class="form-row">Todesk   ID：@item.ToDeskId</span>
                        <span class="form-row">Todesk 密码：@item.ToDeskPsw</span>
                    </div>

                    <div class="form-group">
                        <span class="form-row">连接次数：@item.OraySunCount</span>
                        <span class="form-row">向日葵   ID：@item.OraySunId</span>
                        <span class="form-row">向日葵 密码：@item.OraySunPsw</span>
                    </div>
                    <a asp-controller="Device" asp-action="Create" class="btn btn-primary">新增</a>
                    <a asp-controller="Device" asp-action="Delete" asp-route-guidCode=@item.GuidCode class="btn btn-primary">删除</a>
                    <a asp-controller="Device" asp-action="Modify" asp-route-guidCode=@item.GuidCode class="btn btn-primary">修改</a>
                    <a asp-controller="Device" asp-action="Details" asp-route-guidCode=@item.GuidCode class="btn btn-primary">查看</a>

                </div>
            </div>
        }
    }
    else
    {
        <p>当前没有找到该设备相关信息！</p>
    }
    
</div>

@*<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item disabled">
            <a class="page-link">上一页</a>
        </li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
            <a class="page-link" href="#">下一页</a>
        </li>
    </ul>
</nav>*@

<br />
Page @(Model?.PageCount < Model?.PageNumber ? 0 : Model?.PageNumber) of @Model?.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page}))
@*@(Html.Pager(Model)
    .Url(page => Url.Action("Index", new { page }))
    .Build())*@

RemoteToolServer/Views/Home/Unsupported.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
<div style="margin:120px auto;width:300px">
    <img style="margin:0 auto" src="~/img/under_construction.gif" />
</div>
<div class="text-center">
    <h1 class="display-4">正在玩命开发中，敬请期待！</h1>
    <p>请先选择 <a asp-controller="home" asp-action="index">返回主界面</a>.</p>
</div>